sonar.projectKey=helloworld
sonar.projectName=helloworld
sonar.sources=.
sonar.host.url=http://host.docker.internal:9090
sonar.token=squ_c7f2ef74edd777221b2cc3c3c7c7c6d4980d78ab
sonar.python.version=3
